# theme = "nord_transparent" 
# theme = "base16_transparent"
theme = "tokyonight"

[editor]
line-number = "relative"
scrolloff = 5
bufferline = "multiple"
text-width = 80
true-color = true
rulers = [81, 120]

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "⸽"

[editor.soft-wrap]
enable = false
wrap-indicator = "↪ "
wrap-at-text-width = true

[editor.file-picker]
hidden = false
