[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 8, unit = "/t" }

[[language]]
name = "bash"
shebangs = ["sh","ksh","bash"]
indent = { tab-width = 8, unit = "/t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "/t" }