# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x15161E'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }
    
# My own stuffs
window:
  dynamic_padding: true
  opacity: 0.85
  padding:
    x: 4 
    y: 4 

font:
  normal:
    family: FantasqueSansMono Nerd Font
  bold:
    family: FantasqueSansMono Nerd Font
  italic:
    family: FantasqueSansMono Nerd Font
  bold_italic:
    family: FantasqueSansMono Nerd Font
  size: 10

