#!/bin/ksh

# pkglocatedb is intended to be a more complete pkg_info
install_system_tools="pkglocatedb htop"
install_terminals="alacritty rxvt-unicode--everything cool-retro-term"
install_utilities="ranger lf pcmanfm xarchiver deluge"
install_text_editors="helix neovim"
# xdotool can be used to issue commands to X, to automate CWM?
install_de_tools="scrot feh screenfetch picom xdotool lxappearance"
install_drivers="intel-media-driver"
install_browsers="firefox chromium"
install_dev_tooling="tree-sitter gdb git"
install_c_tools="clang-tools-extra cmake"
install_rust_tools="rust rust-analyzer rust-clippy rust-rustfmt rust-src"
install_fonts="noto-cjk noto-emoji noto-fonts fantasque-sans ubuntumono-nerd-fonts"
install_games="widelands openttd"
install_media_players="vlc"

doas pkg_add \
$install_system_tools \
$install_terminals \
$install_utilities \
$install_text_editors \
$install_de_tools \
$install_themes \
$install_drivers \
$install_browsers \
$install_dev_tooling \
$install_c_tools \
$install_rust_tools \
$install_fonts \
$install_games \
$install_media_players 
