#!/bin/ksh

# Create a backup folder for all the old stuff
randomnumber=$((RANDOM%999999+1))
rm -rf backup_$randomnumber
mkdir backup_$randomnumber
cd backup_$randomnumber
mkdir home
mkdir config
mkdir localbin
mkdir xenodm
mkdir etc
mkdir wallpapers
cd ..

# Not deleting any files accidentally un-tracked, just in case it's a mistake.

for k in .kshrc .profile .xsession .cwmrc .Xresources
do
	mv home/$k backup_$randomnumber/home/$k
	cp ~/$k home/$k
done

for k in mystat powertool
do
	mv localbin/$k backup_$randomnumber/localbin/$k
	cp ~/.local/bin/$k localbin/$k
done

for k in alacritty helix picom ranger
do
	mv config/$k backup_$randomnumber/config/$k
	cp -r ~/.config/$k config/$k
done

for k in Xsetup_0 Xresources
do
	mv xenodm/$k backup_$randomnumber/xenodm/$k
	cp /etc/X11/xenodm/$k xenodm/$k
done

for k in wsconsctl.conf rc.conf.local
do
	mv etc/$k backup_$randomnumber/etc/$k
	cp /etc/$k etc/$k
done

mv wallpapers/* backup_$randomnumber/wallpapers/
cp -r ~/Pictures/Wallpapers ./wallpapers
