#!/usr/bin/env bash

# Powertools for OpenTurde
# Depends on bash because I want to be able to do
#	read -n 1 input

# TODO: See if I can make "command mystat alacritty exec powertool" in .cwmrc

###
#	GENERAL VARIABLE INITIALISATION
###

quit=0
screen=0

# TODO: Test this:
# read -t 1 -n 1 && dosomething
# or maybe
# read -t 1 -n 1 input && echo input

# TODO: When using df to gather data, use df -P and calc from Blocks

# TODO: So this way we can grab input or, if none, just update or whatever
testfunction () {
	read -t 1 -n 1 input
	if [ "$input" == 'q' ]; then
		exit $error_code
	fi
	cputemp=$(sysctl hw.sensors.cpu0.temp0 | cut -d '=' -f2 | cut -d '.' -f1)
	echo $cputemp
}

###
#	SCREENS
###

#	A stats screen - basically the stuff in mystat
#	Screen screen - control brightness, backgrounds(?) etc
#	Network screen - detailed stats, up/down, search, connect etc
#	Packages screen - count, update, search, search installed, etc
#	Config screen - update, refresh, copy to openturde, etc
#			(eg. quickly access openturde tracked files)
#	Shutdown/reboot screen

###
#	MAIN LOOP
###

main_loop () {
	while [ "$quit" -ne 1 ]
	do
		echo "Testing Testing"
	done
}

###
#	START EXECUTION
###

clear
stty -echo

main_loop

stty echo
exit $error_code
