#!/usr/bin/env bash

# Powertools for OpenTurde
# Depends on bash because I want to be able to do
#	read -n 1 input



clear
# TODO: Replace mystat with an internal set of functions
# mystat
time_to_die () {
	# TODO: Here we could use xdotools to move this window to the center?
	# TODO: Turn off echoing of input
	# TODO: Figure out how to read only one character and act without an Enter key
	echo "[S]hutdown     [R]eboot     [C]ancel"
	read input
	case $input in
		S|s|Shutdown|shutdown)
			shutdown -p now
			;;
		R|r|Reboot|reboot)
			shutdown -r now
			;;
		*)
			;;
	esac
}

quit=0
error_code=0
selection=0

take_input () {
	stty -echo
	read -n 1 input
	selection=$input
	echo $input
	echo $selection
	stty echo
}

update_page () {
	if [ $selection == 'f' ]; then
		echo "effeffeff"
	fi
	if [ $selection == 'q' ]; then
		quit=1
	fi
}

debug_output () {
	echo "quit:       $quit"
	echo "error_code: $error_code"
	echo "selection:  $selection"
	echo "input:      $input"
}

while [ $quit -ne 1 ]; do
	take_input
	update_page
	debug_output
done

exit $error_code
