#!/bin/ksh

# File should reside in a user's local drive structure (TODO: add to install script)
# TODO: Add a config section up top that defines a location for user-configurations, which can then be read at run-time to personalise display.

# Will become a little management script
#commands like and for:
#	ifconfig iwx0 scan (with some filtering for purdiness?)
#	ifconfig iwx join XXXX (to join something) and -join
#
#Needs a good dive into man ifconfig to set up a good one.

# TODO:
# Get a list of /etc/hostname.* files through ls, grep and cut
# Then display them in a purdy way to the user
# Devices with active connection should highlight
retrieve_network_devices () {
	wifi_devices_raw=$(ls /etc | grep hostname)
	# TODO: Loop through those and remove the "hostname." bit
}


list_network_devices () {
	
}

# TODO:
# Selection of interface to manipulate
# Scanning function
# Joining function
# unJoining function
# Function to "down" all/specific devices
# Function to "up" all/specific devices